In [63]:
## Importar librerias necesarias
import pandas as pd
import sqlalchemy as sqlal

In [64]:
## Conexion con la base de datos mariaDB
## modificar usuario, contraseña, host, puerto y el nombre de la base de datos
engine = sqlal.create_engine("mariadb+pymysql://root:admin@127.0.0.1:3307/db_programa_educativo?charset=utf8mb4")
conn = engine.connect()

In [65]:
## Obtener motivos de baja (baja de empresa, baja de programa y suspendidos)
query = "SELECT UPPER(motivo) AS motivo, id_estatus_act FROM historial_estatus WHERE id_estatus_act IN (2,3,7)"
df_motivos = pd.read_sql(query, conn)

## modificar el nombre de la columna id_estatus_act por frecuencia
df_motivos.rename(columns={'id_estatus_act': 'frecuencia'}, inplace=True)

df_motivos.head()

                   motivo  frecuencia
0  DESPIDOS DE LA EMPRESA           2
1  DESPIDOS DE LA EMPRESA           2
2  DESPIDOS DE LA EMPRESA           2
3  DESPIDOS DE LA EMPRESA           2
4  DESPIDOS DE LA EMPRESA           2

In [66]:
## Generar la tabla pivot de los motivos de baja
pivot_motivos_baja = (
    df_motivos.groupby(['motivo'])['frecuencia']
    .count()
    .reset_index()
)

print(pivot_motivos_baja)

                            motivo  frecuencia
0           DESPIDOS DE LA EMPRESA           8
1  FALTA DE INTERES EN EL PROGRAMA           2
2             PROBLEMAS FAMILIARES           1
3     SUSPENDIDO POR FALTA DE PAGO           2

In [67]:
## Obtener el total de los motivos 
query = "SELECT COUNT(*) total_motivos FROM historial_estatus WHERE id_estatus_act IN (2,3,7)"
df_total_mot = pd.read_sql(query, conn)
df_total_mot.head()

   total_motivos
0             13

In [68]:
## Agregar la columna total_motivos en la tabla pivot
pivot_motivos_baja = pd.merge(pivot_motivos_baja, df_total_mot, how='cross')
print(pivot_motivos_baja)

                            motivo  frecuencia  total_motivos
0           DESPIDOS DE LA EMPRESA           8             13
1  FALTA DE INTERES EN EL PROGRAMA           2             13
2             PROBLEMAS FAMILIARES           1             13
3     SUSPENDIDO POR FALTA DE PAGO           2             13

In [69]:
## Sacar la tasa de frecuencia de los motivos
pivot_motivos_baja['tasa_frecuencia'] = (pivot_motivos_baja['frecuencia'] / pivot_motivos_baja['total_motivos'] * 100).round(2)
pivot_motivos_baja['tasa_frecuencia'] =  pivot_motivos_baja['tasa_frecuencia'].fillna(0)
print(pivot_motivos_baja)

                            motivo  frecuencia  total_motivos  tasa_frecuencia
0           DESPIDOS DE LA EMPRESA           8             13            61.54
1  FALTA DE INTERES EN EL PROGRAMA           2             13            15.38
2             PROBLEMAS FAMILIARES           1             13             7.69
3     SUSPENDIDO POR FALTA DE PAGO           2             13            15.38

In [70]:
# Ordenar la tabla pivote pivot_motivos_baja por la columna tasa_frecuencia en orden descendente
pivot_motivos_baja = pivot_motivos_baja.sort_values(by=['tasa_frecuencia'], ascending=False) 
print(pivot_motivos_baja)

                            motivo  frecuencia  total_motivos  tasa_frecuencia
0           DESPIDOS DE LA EMPRESA           8             13            61.54
1  FALTA DE INTERES EN EL PROGRAMA           2             13            15.38
3     SUSPENDIDO POR FALTA DE PAGO           2             13            15.38
2             PROBLEMAS FAMILIARES           1             13             7.69